services:
  fastapi:
    image: jkhandockerlab420/fastapi:v1
    container_name: fastapi
    ports:
      - "8000:8000"

  streamlit:
    image: jkhandockerlab420/streamlit:v1
    container_name: streamlit
    ports:
      - "8501:8501"
    environment:
      API_URL: http://fastapi:8000
